In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import SGDClassifier
import warnings
from sklearn.metrics import classification_report, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.model_selection import train_test_split

data_raw = pd.read_csv('data.csv', sep=',')
data = data_raw.copy(deep=True)
#data.columns
print(data.head())
#----------------------------------
print('*'*50)
print('Valores famhist: \n', data.famhist.value_counts())
print('*'*50)
print('Valores chd: \n', data.chd.value_counts())
#---------------------------------
famhist = data.famhist.map({'Present':0, 'Absent':1})
print('Valores famhist Transformados: \n', famhist.value_counts())
#-----------------------------------




   sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
1  160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
2  144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
3  118     0.08  3.48      32.28  Present     52    29.14     3.81   46    0
4  170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
5  134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1
**************************************************
Valores famhist: 
 Absent     270
Present    192
Name: famhist, dtype: int64
**************************************************
Valores chd: 
 0    302
1    160
Name: chd, dtype: int64
Valores famhist Transformados: 
 1    270
0    192
Name: famhist, dtype: int64


# Classificacao CHD

In [3]:
sgd = SGDClassifier(random_state=42)
chd = data.chd
for column in data.columns:
        try:
            label = data[column]
            label = label[:,np.newaxis]
            try:
                train_x, test_x, train_y, test_y = train_test_split(label,chd)
                sgd.fit(train_x, train_y)
                target_train = (train_y==1)
                target_test = (test_y==1)
                y_train_pred = sgd.predict(train_x)
                y_test_pred = sgd.predict(test_x)
                print( column.upper() ,'por CHD')
                print('='*50)
                print(classification_report(target_test, y_test_pred))
                print('*'*25)
                print('Matrix_train : \n', confusion_matrix(target_train, y_train_pred))
                print('.'*25)
                print('Matrix_test : \n', confusion_matrix(target_test, y_test_pred))
                print('*'*25)
            except:
                print('*****Erro 2*******')
        except:
            print('Erro 1')
        

SBP por CHD
              precision    recall  f1-score   support

       False       0.00      0.00      0.00        81
        True       0.30      1.00      0.46        35

    accuracy                           0.30       116
   macro avg       0.15      0.50      0.23       116
weighted avg       0.09      0.30      0.14       116

*************************
Matrix_train : 
 [[  0 221]
 [  0 125]]
.........................
Matrix_test : 
 [[ 0 81]
 [ 0 35]]
*************************
TOBACCO por CHD
              precision    recall  f1-score   support

       False       0.85      0.28      0.42        78
        True       0.38      0.89      0.53        38

    accuracy                           0.48       116
   macro avg       0.61      0.59      0.48       116
weighted avg       0.69      0.48      0.46       116

*************************
Matrix_train : 
 [[ 81 143]
 [ 13 109]]
.........................
Matrix_test : 
 [[22 56]
 [ 4 34]]
*************************
LDL por CHD


/home/leleopc/Downloads/conda/envs/Env1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/leleopc/Downloads/conda/envs/Env1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/leleopc/Downloads/conda/envs/Env1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [4]:
sgd = SGDClassifier(random_state=42)
for column in data.columns:
        try:
            label = data[column]
            label = label[:,np.newaxis]
            try:
                train_x, test_x, train_y, test_y = train_test_split(label,famhist)
                sgd.fit(train_x, train_y)
                target_train = (train_y==1)
                target_test = (test_y==1)
                y_train_pred = sgd.predict(train_x)
                y_test_pred = sgd.predict(test_x)
                print( column.upper() ,'por FAMHIST')
                print('='*50)
                print(classification_report(target_test, y_test_pred))
                print('*'*25)
                print('Matrix_train : \n', confusion_matrix(target_train, y_train_pred))
                print('.'*25)
                print('Matrix_test : \n', confusion_matrix(target_test, y_test_pred))
                print('*'*25)
                
                
                
            except:
                print('Erro 2')
        except:
            print('Erro 1')


SBP por FAMHIST
              precision    recall  f1-score   support

       False       0.00      0.00      0.00        47
        True       0.59      1.00      0.75        69

    accuracy                           0.59       116
   macro avg       0.30      0.50      0.37       116
weighted avg       0.35      0.59      0.44       116

*************************
Matrix_train : 
 [[  0 145]
 [  0 201]]
.........................
Matrix_test : 
 [[ 0 47]
 [ 0 69]]
*************************
TOBACCO por FAMHIST
              precision    recall  f1-score   support

       False       0.51      0.75      0.60        55
        True       0.60      0.34      0.44        61

    accuracy                           0.53       116
   macro avg       0.55      0.54      0.52       116
weighted avg       0.56      0.53      0.52       116

*************************
Matrix_train : 
 [[111  26]
 [137  72]]
.........................
Matrix_test : 
 [[41 14]
 [40 21]]
*************************
LDL 

/home/leleopc/Downloads/conda/envs/Env1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/leleopc/Downloads/conda/envs/Env1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/leleopc/Downloads/conda/envs/Env1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/leleopc/Downloads/conda/envs/Env1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and b

In [5]:
data_1 = data.drop(columns={'chd','famhist'})
sgd = SGDClassifier(random_state=42)
  
    
train_x, test_x, train_y, test_y = train_test_split(data_1,chd)
sgd.fit(train_x, train_y)
target_train = (train_y==1)
target_test = (test_y==1)
y_train_pred = sgd.predict(train_x)
y_test_pred = sgd.predict(test_x)
print(classification_report(target_test, y_test_pred))
print('*'*25)
print('Matrix_train : \n', confusion_matrix(target_train, y_train_pred))
print('.'*25)
print('Matrix_test : \n', confusion_matrix(target_test, y_test_pred))
print('*'*25)

                
                
            

              precision    recall  f1-score   support

       False       0.58      0.99      0.73        67
        True       0.50      0.02      0.04        49

    accuracy                           0.58       116
   macro avg       0.54      0.50      0.38       116
weighted avg       0.55      0.58      0.44       116

*************************
Matrix_train : 
 [[233   2]
 [108   3]]
.........................
Matrix_test : 
 [[66  1]
 [48  1]]
*************************


In [6]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
data_2 = minmax.fit_transform(data_1)
sgd = SGDClassifier(random_state=42)
  
    
train_x, test_x, train_y, test_y = train_test_split(data_2,chd)
sgd.fit(train_x, train_y)
target_train = (train_y==1)
target_test = (test_y==1)
y_train_pred = sgd.predict(train_x)
y_test_pred = sgd.predict(test_x)
print(classification_report(target_test, y_test_pred))
print('*'*25)
print('Matrix_train : \n', confusion_matrix(target_train, y_train_pred))
print('.'*25)
print('Matrix_test : \n', confusion_matrix(target_test, y_test_pred))
print('*'*25)


              precision    recall  f1-score   support

       False       0.65      0.97      0.78        74
        True       0.60      0.07      0.13        42

    accuracy                           0.65       116
   macro avg       0.62      0.52      0.45       116
weighted avg       0.63      0.65      0.54       116

*************************
Matrix_train : 
 [[226   2]
 [105  13]]
.........................
Matrix_test : 
 [[72  2]
 [39  3]]
*************************


In [7]:
import matplotlib.pyplot as plt
from sklearn.naive_bayes import BernoulliNB, MultinomialNB
#scalar = MinMaxScaler()
#X = scalar.fit_transform(X)
train_x, test_x, train_y, test_y = train_test_split(data.age[:,np.newaxis],chd)
bnb = BernoulliNB(binarize=0.5)
mnb = MultinomialNB()
#------------------
bnb.fit(train_x,train_y)
mnb.fit(train_x,train_y)
#---------------------
print('Bernulli Score:', bnb.score(test_x,test_y))
print('Multinomial Score:', mnb.score(test_x,test_y))

Bernulli Score: 0.6982758620689655
Multinomial Score: 0.6982758620689655


In [30]:


data_chunk = pd.read_csv('data.csv', chunksize=10)

mnb = MultinomialNB(class_prior=[.22,.78])
test = data.sample(200)

#* Pegar dados Truncados cada vez e Faz o fitting do modelo e gradualmente improva a si

for idx, data_sample in enumerate(data_chunk):
    print('Robo: ',idx)
    data_sample = test
    #data_sample = data_sample[data_sample.chd >= 1]
    #-------------------------------------
    train_x, test_x, train_y, test_y = train_test_split(data_sample, data_sample.chd, test_size=.3)
    mnb.partial_fit(train_x[:,np.newaxis],train_y, classes=[0,1])
    y_pred = mnb.predict(test_x[:,np.newaxis])
    print(confusion_matrix(y_pred=y_pred, y_true=test_y))


Robo:  0


TypeError: '(slice(None, None, None), None)' is an invalid key

In [9]:
data.describe

<bound method NDFrame.describe of      sbp  tobacco    ldl  adiposity  famhist  typea  obesity  alcohol  age  \
1    160    12.00   5.73      23.11  Present     49    25.30    97.20   52   
2    144     0.01   4.41      28.61   Absent     55    28.87     2.06   63   
3    118     0.08   3.48      32.28  Present     52    29.14     3.81   46   
4    170     7.50   6.41      38.03  Present     51    31.99    24.26   58   
5    134    13.60   3.50      27.78  Present     60    25.99    57.34   49   
..   ...      ...    ...        ...      ...    ...      ...      ...  ...   
459  214     0.40   5.98      31.72   Absent     64    28.45     0.00   58   
460  182     4.20   4.41      32.10   Absent     52    28.61    18.72   52   
461  108     3.00   1.59      15.23   Absent     40    20.09    26.64   55   
462  118     5.40  11.61      30.79   Absent     64    27.35    23.97   40   
463  132     0.00   4.82      33.41  Present     62    14.70     0.00   46   

     chd  
1      1  
2      